project_id = "nepnxpmuuawjozigkpvo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions]
enabled = true

[functions.create-user]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.device-session]
verify_jwt = false

[functions.session-guard]
verify_jwt = false

[functions.user-sessions]
verify_jwt = true

[functions.public-menu]
verify_jwt = false

[functions.table-order-create]
verify_jwt = false

[functions.online-order-create]
verify_jwt = false

[functions.order-actions]
verify_jwt = false